server:
  port: 8082

spring:
  application:
    name: calculation-service

eureka:
  instance:
    preferIpAddress: true
    hostname: calculation-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
